[2025-10-06T16:28:46.745+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: kmeans_dag.run_elbow_task manual__2025-10-06T16:23:42.178672+00:00 [queued]>
[2025-10-06T16:28:46.751+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: kmeans_dag.run_elbow_task manual__2025-10-06T16:23:42.178672+00:00 [queued]>
[2025-10-06T16:28:46.751+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-06T16:28:46.751+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2025-10-06T16:28:46.752+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-06T16:28:46.757+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_elbow_task> on 2025-10-06 16:23:42.178672+00:00
[2025-10-06T16:28:46.761+0000] {standard_task_runner.py:55} INFO - Started process 3789 to run task
[2025-10-06T16:28:46.763+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'kmeans_dag', 'run_elbow_task', 'manual__2025-10-06T16:23:42.178672+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/kmeans_dag.py', '--cfg-path', '/tmp/tmpu3es4byf']
[2025-10-06T16:28:46.764+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask run_elbow_task
[2025-10-06T16:28:46.798+0000] {task_command.py:388} INFO - Running <TaskInstance: kmeans_dag.run_elbow_task manual__2025-10-06T16:23:42.178672+00:00 [running]> on host 7ba1f4109bc7
[2025-10-06T16:28:46.827+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=kmeans_dag
AIRFLOW_CTX_TASK_ID=run_elbow_task
AIRFLOW_CTX_EXECUTION_DATE=2025-10-06T16:23:42.178672+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-06T16:23:42.178672+00:00
[2025-10-06T16:28:46.836+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kmeans_dag.py", line 36, in task_elbow
    compute_elbow(df, max_k=10)
NameError: name 'compute_elbow' is not defined
[2025-10-06T16:28:46.839+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=kmeans_dag, task_id=run_elbow_task, execution_date=20251006T162342, start_date=20251006T162846, end_date=20251006T162846
[2025-10-06T16:28:46.844+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task run_elbow_task (name 'compute_elbow' is not defined; 3789)
[2025-10-06T16:28:46.859+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-06T16:28:46.870+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
